name: media_viewer
description: A cross-platform media viewer app for images and videos.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Storage & file handling
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  file_picker: ^9.2.1
  permission_handler: ^11.4.0
  get_it: ^8.0.3

  # Media handling
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_native_event_loop: ^1.0.9
  # Linux support packages
  media_kit_libs_linux: ^1.1.3
  photo_view: ^0.15.0
  video_player: ^2.9.3
  chewie: ^1.11.0
  flutter_cache_manager: ^3.4.1
  transparent_image: ^2.0.1
  path: ^1.9.1
  crypto: ^3.0.6
  image: ^4.5.3

  # Google Drive integration
  googleapis: ^14.0.0
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.3.0
  http: ^1.3.0

  # HEIC handling
  heic_to_jpg: ^0.2.0

  # UI components
  table_calendar: ^3.2.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.5

  # For desktop
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
